name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: gopath/github.com/katydid/validator-go
    - name: Checkout gogoprotobuf
      uses: actions/checkout@v4
      with:
        repository: gogo/protobuf
        path: gopath/github.com/gogo/protobuf
    - name: Checkout testuit
      uses: actions/checkout@v4
      with:
        repository: katydid/testsuite
        path: gopath/github.com/katydid/testsuite
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Fetch dependencies
      run: |
        cd gopath/github.com/katydid/validator-go
        go mod download -x
    - name: Install tools
      run: |
        cd gopath/github.com/katydid/validator-go
        go install -x github.com/goccmack/gocc
        go install -x github.com/awalterschulze/goderive
        go install -x github.com/gogo/protobuf/protoc-gen-gogo
    - name: Setup protoc
      run: |
        cd gopath/github.com/katydid/validator-go
        ./install_protoc.sh
    - name: Protoc version
      run: |
        cd gopath/github.com/katydid/validator-go
        PATH=$HOME/bin:$PATH protoc --version
    - name: env
      run: env && go env && pwd
    - name: tree
      run: tree
    - name: Generate
      run: |
        cd gopath/github.com/katydid/validator-go
        PATH=$HOME/bin:$PATH make regenerate
    - name: Build
      run: |
        cd gopath/github.com/katydid/validator-go
        make build
    - name: Test
      run: |
        cd gopath/github.com/katydid/validator-go
        make test
    - name: Vet
      run: |
        cd gopath/github.com/katydid/validator-go
        make vet
    - name: Errcheck
      run: |
        cd gopath/github.com/katydid/validator-go
        make errcheck
    - name: Checklicencse
      run: |
        cd gopath/github.com/katydid/validator-go
        make checklicense
    - name: Diff
      run: |
        cd gopath/github.com/katydid/validator-go
        make diff
