name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Fetch dependencies
      run: go mod download -x
    - name: Install tools
      run: go install -x github.com/kisielk/errcheck golang.org/x/lint/golint github.com/goccmack/gocc github.com/awalterschulze/goderive github.com/gogo/protobuf
    - name: Generate
      run: make regenerate
    - name: Build
      run: make build
    - name: Test
      run: make test
    - vet:
      run: make vet
    - errcheck:
      run: make errcheck
    - checklicencse:
      run: make checklicense
    - diff:
      run: make diff
