name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Fetch dependencies
      run: go mod download -x
    - name: Install tools
      run: go install -x github.com/goccmack/gocc github.com/awalterschulze/goderive github.com/gogo/protobuf/protoc-gen-gogo
    - name: Setup protoc
      run: |
        ls -la
        tree
        bash ${GITHUB_WORKSPACE}/install-protoc.sh
    - name: Generate
      run: make regenerate
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Vet
      run: make vet
    - name: Errcheck
      run: make errcheck
    - name: Checklicencse
      run: make checklicense
    - name: Diff
      run: make diff
