name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Checkout gogoprotobuf
      uses: actions/checkout@v4
      with:
        repository: gogo/protobuf
        path: ../protobuf
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Fetch dependencies
      run: go mod download -x
    - name: Install tools
      run: go install -x github.com/goccmack/gocc github.com/awalterschulze/goderive github.com/gogo/protobuf/protoc-gen-gogo
    - name: Setup protoc
      run: ./install_protoc.sh
    - name: Protoc version
      run: PATH=$HOME/bin:$PATH protoc --version
    - name: env
      run: env && go env && pwd
    - name: tree
      run: cd .. && tree
    - name: Generate
      run: PATH=$HOME/bin:$PATH make regenerate
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Vet
      run: make vet
    - name: Errcheck
      run: make errcheck
    - name: Checklicencse
      run: make checklicense
    - name: Diff
      run: make diff
